#include "optifine/emit.h"

int emit_program_prologue(FILE *out) {
    fprintf(out,
            "; AUTO-GENERATED by optifine -- do not hand-edit, regenerate instead\n"
            "; (unlike sim/fixtures/ms1_*/ms2_*, which are genuinely hand-written).\n"
            ".arch atmega128\n\n.section .text\n.global _start\n\n_start:\n");
    return 0;
}

int emit_program_epilogue(FILE *out) {
    fprintf(out, "    break               ; halt simulation\n");
    return 0;
}

int emit_candidate(const Candidate *candidate, FILE *out) {
    for (size_t i = 0; i < candidate->num_instructions; i++) {
        const AvrInstr *instr = &candidate->instructions[i];
        fprintf(out, "    %s", instr->mnemonic);
        for (int j = 0; j < instr->num_operands; j++) {
            fprintf(out, "%s%s", j == 0 ? " " : ", ", instr->operands[j]);
        }
        fprintf(out, "\n");
    }
    return 0;
}
